### PR TITLE
fix: undefined injectedGlobalOptions close #182

### LINKED ISSUE #182: [Bug Report] undefined injectedGlobalOptions
### Bug 描述 Bug description
In the usePagination function we are running into the problem that `injectedGlobalOptions` are undefined in this line 
```pagination: (_injectedGlobalOption = injectedGlobalOptions.pagination) !== null && _injectedGlobalOption !== void 0 ? _injectedGlobalOption : {}```
When just replacing `injectedGlobalOptions.pagination` with `injectedGlobalOptions?.pagination` it works.

### 代码重现 Reproduce
I honestly dont know how to reproduce it.

### 期望结果 Desired result
No undefined error and breaking the code.

### PR DESCRIPTION
**Pull request by LuXDAmore**
fix: undefined injectedGlobalOptions close #182

### CODE REVIEW

**Comment by John60676** [comment]
Can you provide a reproducible example?

**Comment by LuXDAmore** [comment]
@John60676 So, I don't know exactly how to reproduce it and probably it's not a problem of `vue-request`..
After digging I've found that is related to Nuxt and to [this bug](https://github.com/nuxt/nuxt/issues/25029)

Because moving the `usePagination()` BEFORE the `await useAsyncData()` fix the problem.

So i think in some ways the `inject` lose its context after the `await` so the `undefined injectedGlobalOptions` error appear in the console and is annoying.

**Comment by neostfox** [comment]
when  usePagination used in typescript or JavaScript， inject will return undefined。

**Comment by neostfox** [comment]
I think use renderless component is much better than provide/inject

**Comment by sugionosihuahua** [comment]
@LuXDAmore @John60676 @neostfox , so everyone? how to fix this? i have this problem when implementing ant-design-vue ajax table in vue js and i can't found any related post/thread except this

**Comment by sugionosihuahua** [comment]
@LuXDAmore thx for the reply, however in my case this happened because i put data result inside another array in the backend response (same as documentation in the ant-design-vue table, they put data in the "results" key).
so now i can do just fine.

**Comment by code-lixm** [comment]
i also meet the problem, plz merge the pr

**Pull request closed without merging**
